export const AllIndustries = {
  PL: [
    { value: 1, label: "Fryzjer" },
    { value: 2, label: "Salon kosmetyczny" },
    { value: 3, label: "Paznokcie" },
    { value: 4, label: "Brwi i rzęsy" },
    { value: 5, label: "Makijaż" },
    { value: 6, label: "Fizjoterapia" },
    { value: 7, label: "Studio Tatuażu" },
    { value: 8, label: "Barber" },
    { value: 9, label: "Masaż" },
    { value: 10, label: "Trener personalny" },
    { value: 11, label: "Medycyna Estetyczna" },
    { value: 12, label: "Zdrowie" },
    { value: 13, label: "Dietetyk" },
    { value: 14, label: "Depilacja" },
    { value: 15, label: "Piercing" },
    { value: 16, label: "Psychoterapia" },
    { value: 17, label: "Zakupy" },
    { value: 18, label: "Motoryzacja" },
    { value: 19, label: "Telekomunikacja" },
    { value: 20, label: "Elektronika" },
    { value: 21, label: "Hotele, motele" },
    { value: 22, label: "Warsztaty samochodowe, serwisy naprawcze" },
    { value: 23, label: "Instytucje finansowe" },
    { value: 0, label: "Inne" },
  ],
  EN: [
    { value: 1, label: "Hairdresser" },
    { value: 2, label: "Beauty studio" },
    { value: 3, label: "Nails" },
    { value: 4, label: "Eyebrows and eyelashes" },
    { value: 5, label: "Makeup" },
    { value: 6, label: "Physiotherapy" },
    { value: 7, label: "Tattoo studio" },
    { value: 8, label: "Barber" },
    { value: 9, label: "Massage" },
    { value: 10, label: "Personal trainer" },
    { value: 11, label: "Aesthetic medicine" },
    { value: 12, label: "Health" },
    { value: 13, label: "Dietician" },
    { value: 14, label: "Epilation" },
    { value: 15, label: "Piercing" },
    { value: 16, label: "Psychotherapy" },
    { value: 17, label: "Shopping" },
    { value: 18, label: "Automotive" },
    { value: 19, label: "Telecommunication" },
    { value: 20, label: "Electronics" },
    { value: 21, label: "Hotels, motels" },
    { value: 22, label: "Car workshops, repair services" },
    { value: 23, label: "Financial institutions" },
    { value: 0, label: "Other" },
  ],
}