export const AllIndustries = [
  { id: 325, name: "Salony fryzjerskie" },
  { id: 326, name: "Salony kosmetyczne, odnowa biologiczna, SPA" },
  { id: 436, name: "Salony makijażu" },
  { id: 437, name: "Serwisy komputerowe" },
  { id: 1, name: "Administracja państwowa" },
  { id: 2, name: "Aerozole" },
  { id: 3, name: "AGD" },
  { id: 4, name: "Agencja aktorska, aktorzy" },
  { id: 5, name: "Agencja filmowa" },
  { id: 6, name: "Agencja Reklamowa" },
  { id: 7, name: "Agencja turystyczna" },
  { id: 8, name: "Agencje artystyczne" },
  { id: 9, name: "Agencje modelek i hostess" },
  { id: 10, name: "Agencje, składy celne" },
  { id: 11, name: "Agroturystyka" },
  { id: 12, name: "Akumulatory, baterie, źródła zasilania" },
  { id: 13, name: "Alarmy, zabezpieczenia antywłamaniowe" },
  { id: 14, name: "Anteny" },
  { id: 15, name: "Antyki, dzieła sztuki" },
  { id: 16, name: "Antykorozyjne roboty, zabezpieczenia" },
  { id: 17, name: "Antykwariaty" },
  { id: 18, name: "Aparaty słuchowe, implanty ślimakowe" },
  { id: 19, name: "Apartamenty" },
  { id: 20, name: "Apteki" },
  { id: 21, name: "Architekci" },
  { id: 22, name: "Architektura krajobrazu" },
  { id: 23, name: "Architektura wnętrz" },
  { id: 24, name: "Archiwizacyjne usługi" },
  { id: 25, name: "Armatura przemysłowa" },
  { id: 26, name: "Artykuły dziecięce" },
  { id: 27, name: "Artykuły jednorazowe, higieniczne" },
  { id: 28, name: "Artykuły jeździeckie" },
  { id: 29, name: "Artykuły pościelowe, ręczniki, koce" },
  { id: 30, name: "Artykuły ślubne i weselne" },
  { id: 31, name: "Artykuły spożywcze" },
  { id: 32, name: "Artykuły szkolne, biurowe" },
  { id: 33, name: "Audiowizualne systemy" },
  { id: 34, name: "Audytorskie usługi" },
  { id: 35, name: "Automaty do sprzedaży" },
  { id: 36, name: "Automatyka przemysłowa" },
  { id: 37, name: "Autoryzowany serwis samochodowy" },
  { id: 38, name: "Badanie rynku i opinii publicznej" },
  { id: 39, name: "Banki" },
  { id: 40, name: "Baseny, fontanny" },
  { id: 41, name: "Bazy danych, usługi informacyjne, wywiadownie" },
  { id: 42, name: "Beton" },
  { id: 43, name: "BHP" },
  { id: 44, name: "Biblioteki, czytelnie" },
  { id: 45, name: "Bielizna" },
  { id: 46, name: "Biura ogłoszeń" },
  { id: 47, name: "Biura patentowe" },
  { id: 48, name: "Biura podróży" },
  { id: 49, name: "Biura pośrednictwa pracy" },
  { id: 50, name: "Biura projektów" },
  { id: 51, name: "Biura rachunkowe, doradztwo podatkowe" },
  { id: 52, name: "Blacharstwo, lakiernictwo pojazdowe" },
  { id: 53, name: "Bramy, kraty, ogrodzenia" },
  { id: 54, name: "Brukarstwo" },
  { id: 55, name: "Budownictwo" },
  { id: 56, name: "Campingi" },
  { id: 57, name: "Catering" },
  { id: 58, name: "Centra handlowe, supermarkety, hipermarkety" },
  { id: 59, name: "Ceramika, porcelana" },
  { id: 60, name: "Certyfikacja i kontrola jakości" },
  { id: 61, name: "Certyfikaty energetyczne" },
  { id: 62, name: "Chemia" },
  { id: 63, name: "Chirurgia" },
  { id: 64, name: "Ciepłownictwo, energetyka cieplna" },
  { id: 65, name: "Cukiernictwo" },
  { id: 66, name: "Cukrownie" },
  { id: 67, name: "Cyrki, wesołe miasteczka" },
  { id: 68, name: "Dachy" },
  { id: 69, name: "Dekoracje, wyposażenie wnętrz" },
  { id: 70, name: "Detektywistyczne usługi" },
  { id: 71, name: "Deweloperzy" },
  { id: 72, name: "Dezynfekcja, dezynsekcja, deratyzacja" },
  { id: 73, name: "Dietetyka, odchudzanie" },
  { id: 74, name: "Domy kultury" },
  { id: 75, name: "Domy mediowe" },
  { id: 76, name: "Doradztwo" },
  { id: 77, name: "Drewniane domy" },
  { id: 78, name: "Drewno, wyroby drewniane i drewnopochodne" },
  { id: 79, name: "Drób" },
  { id: 80, name: "Drogi, mosty" },
  {
    id: 81,
    name: "Drukarki, urządzenia peryferyjne, materiały eksploatacyjne",
  },
  { id: 82, name: "Drukarnie, poligrafia" },
  { id: 83, name: "Drukarskie akcesoria, materiały, maszyny" },
  { id: 84, name: "Drzwi" },
  { id: 85, name: "Dyskoteki, kluby" },
  { id: 86, name: "Dywany, wykładziny" },
  { id: 87, name: "Działalność twórcza" },
  { id: 88, name: "Dźwigi i urządzenia dźwigowe" },
  { id: 89, name: "Ekspertyzy, wdrożenia, analizy" },
  { id: 90, name: "Elektroizolacje" },
  { id: 91, name: "Elektronika" },
  { id: 92, name: "Elektrotechnika" },
  { id: 93, name: "Elektrownie" },
  { id: 94, name: "Energetyka" },
  { id: 95, name: "Etykiety, naklejki, emblematy" },
  { id: 96, name: "Farby, lakiery, emalie" },
  { id: 97, name: "Farmaceutyczne produkty" },
  { id: 98, name: "Filmy" },
  { id: 99, name: "Filtry, filtry powietrza" },
  { id: 100, name: "Finansowe usługi" },
  { id: 101, name: "Firany, zasłony" },
  { id: 102, name: "Fitness" },
  { id: 103, name: "Folia i artykuły foliowe" },
  { id: 104, name: "Fotografia" },
  { id: 105, name: "Fundusze inwestycyjne" },
  { id: 106, name: "Fundusze unijne" },
  { id: 107, name: "Galanteria skórzana i z tworzyw sztucznych" },
  { id: 108, name: "Galerie" },
  { id: 109, name: "Gastronomia" },
  { id: 110, name: "Gaz" },
  { id: 111, name: "Gazety i czasopisma" },
  { id: 112, name: "Gazy techniczne" },
  { id: 113, name: "Geodezja, plany, mapy" },
  { id: 114, name: "Glazura i terakota" },
  { id: 115, name: "Gospodarka odpadami, surowce wtórne" },
  { id: 116, name: "Grawerowanie" },
  { id: 117, name: "Grzyby" },
  { id: 118, name: "Hale stalowe" },
  { id: 119, name: "Handel" },
  { id: 120, name: "Hotele, motele" },
  { id: 121, name: "Hurtownie" },
  { id: 122, name: "Hydraulika siłowa" },
  { id: 123, name: "Imprezy, przyjęcia" },
  { id: 124, name: "Informatyka" },
  { id: 125, name: "Instalacje elektryczne, urządzenia" },
  { id: 126, name: "Instalacje grzewcze i ogrzewanie" },
  { id: 127, name: "Instalacje i urządzenia gazowe" },
  { id: 128, name: "Instalacje i urządzenia sanitarne" },
  { id: 129, name: "Instalacje przeciwpożarowe" },
  { id: 130, name: "Instalacje wodno-kanalizacyjne" },
  { id: 131, name: "Instrumenty muzyczne" },
  { id: 132, name: "Instytuty Wojskowe" },
  { id: 133, name: "Instytuty, ośrodki badawczo rozwojowe" },
  { id: 134, name: "Internet i usługi hostingowe" },
  { id: 135, name: "Izolacje, termoizolacje" },
  { id: 136, name: "Jachty, łodzie, statki" },
  { id: 137, name: "Kable, przewody, światłowody" },
  { id: 138, name: "Kadry i płace" },
  { id: 139, name: "Kalendarze" },
  { id: 140, name: "Kamieniarstwo" },
  { id: 141, name: "Kantory, lombardy" },
  { id: 142, name: "Kartki okolicznościowe, pocztówki" },
  { id: 143, name: "Kasy fiskalne" },
  { id: 144, name: "Katalog stron internetowych" },
  { id: 145, name: "Kawa i herbata" },
  { id: 146, name: "Kawiarnie" },
  { id: 147, name: "Kina" },
  { id: 148, name: "Kleje, żywice" },
  { id: 149, name: "Klimatyzacja, wentylacja i chłodnictwo" },
  { id: 150, name: "Kolejowy tabor" },
  { id: 151, name: "Kolektory słoneczne" },
  { id: 152, name: "Kominki, piece, kotły" },
  { id: 153, name: "Kominy, usługi kominiarskie" },
  { id: 154, name: "Komisy samochodowe" },
  { id: 155, name: "Komputery, oprogramowanie, akcesoria" },
  { id: 156, name: "Komunikacja, transport pasażerski" },
  { id: 157, name: "Konstrukcje metalowe, aluminiowe, stalowe" },
  { id: 158, name: "Kopalnie" },
  { id: 159, name: "Kosmetyki" },
  { id: 160, name: "Krawaty" },
  { id: 161, name: "Krawiectwo, haft" },
  { id: 162, name: "Kredyty" },
  { id: 163, name: "Księgarnie" },
  { id: 164, name: "Księgowość" },
  { id: 165, name: "Kwiaciarnie" },
  { id: 166, name: "Kwiaty, rośliny sztuczne" },
  { id: 167, name: "Laboratoria" },
  { id: 168, name: "Lakierowanie proszkowe" },
  { id: 169, name: "Lakierowanie, malowanie" },
  { id: 170, name: "Leasing" },
  { id: 171, name: "Lekarze" },
  { id: 172, name: "Leśnictwo" },
  { id: 173, name: "Lody" },
  { id: 174, name: "Lotnictwo" },
  { id: 175, name: "Łańcuchy" },
  { id: 176, name: "Łazienki" },
  { id: 177, name: "Łożyska" },
  { id: 178, name: "Magazyny, systemy magazynowe, logistyka" },
  { id: 179, name: "Magnesy, elektromagnesy, magnetyzery" },
  { id: 180, name: "Maklerskie biura" },
  { id: 181, name: "Maszty, flagi, sztandary" },
  { id: 182, name: "Maszyny budowlane" },
  { id: 183, name: "Maszyny dla przemysłu spożywczego, mięsnego" },
  { id: 184, name: "Maszyny do obróbki drewna" },
  { id: 185, name: "Maszyny do obróbki metali" },
  { id: 186, name: "Maszyny i urządzenia górnicze" },
  { id: 187, name: "Maszyny szwalnicze, urządzenia prasowalnicze" },
  { id: 188, name: "Materace" },
  { id: 189, name: "Materiały budowlane" },
  { id: 190, name: "Meble" },
  { id: 191, name: "Meble biurowe" },
  { id: 192, name: "Meble kuchenne" },
  { id: 193, name: "Meble metalowe" },
  { id: 194, name: "Meble ogrodowe" },
  { id: 195, name: "Meble szkolne" },
  { id: 196, name: "Meble tapicerowane" },
  { id: 197, name: "Medycyna" },
  { id: 198, name: "Medycyna naturalna" },
  { id: 199, name: "Mięso, wędliny, drób" },
  { id: 200, name: "Militaria, artykuły wojskowe" },
  { id: 201, name: "Mleko i produkty mleczne" },
  { id: 202, name: "Moda ślubna, komunijna" },
  { id: 203, name: "Modelarstwo" },
  { id: 204, name: "Monitoring" },
  { id: 205, name: "Motocykle, quady, skutery" },
  { id: 206, name: "Motoryzacja, akcesoria, usługi motoryzacyjne" },
  { id: 207, name: "Mrożonki" },
  { id: 208, name: "Muzea" },
  { id: 209, name: "Muzyczne zespoły" },
  { id: 210, name: "Myjnie samochodowe" },
  { id: 211, name: "Myślistwo" },
  { id: 212, name: "Młyny" },
  { id: 213, name: "Nadzór budowlany" },
  { id: 214, name: "Nakrycia głowy, rękawiczki, szaliki" },
  { id: 215, name: "Namioty, hale" },
  { id: 216, name: "Napoje alkoholowe" },
  { id: 217, name: "Narzędzia, elektronarzędzia" },
  { id: 218, name: "Nasiona, sadzonki" },
  { id: 219, name: "Nauka jazdy" },
  { id: 220, name: "Nauka tańca" },
  { id: 221, name: "Nawigacja" },
  { id: 222, name: "Nawozy" },
  { id: 223, name: "Nieruchomości" },
  { id: 224, name: "Obiekty sportowe" },
  { id: 225, name: "Obrazy, oprawa obrazów" },
  { id: 226, name: "Obróbka metali, wyroby metalowe, metale kolorowe" },
  { id: 227, name: "Obróbka skrawanie, szlifowanie i frezowanie" },
  { id: 228, name: "Obuwie" },
  { id: 229, name: "Ochrona osób i mienia" },
  { id: 230, name: "Ochrona środowiska, ekologia" },
  { id: 231, name: "Oczyszczanie ścieków" },
  { id: 232, name: "Odkurzacze centralne" },
  { id: 233, name: "Odzież" },
  { id: 234, name: "Odzież ciążowa" },
  { id: 235, name: "Odzież damska" },
  { id: 236, name: "Odzież dziecięca, młodzieżowa" },
  { id: 237, name: "Odzież jeansowa" },
  { id: 238, name: "Odzież męska" },
  { id: 239, name: "Odzież ochronna i robocza" },
  { id: 240, name: "Odzież skórzana" },
  { id: 241, name: "Odzież sportowa" },
  { id: 242, name: "Odzież używana" },
  { id: 243, name: "Odżywki i suplementy" },
  { id: 244, name: "Ogrodnicze usługi, artykuły, sprzęt" },
  { id: 245, name: "Ogrody botaniczne, zoologiczne" },
  { id: 246, name: "Okna" },
  { id: 247, name: "Okucia" },
  { id: 248, name: "Opakowania" },
  { id: 249, name: "Opakowania i pojemniki" },
  { id: 250, name: "Opałowe materiały" },
  { id: 251, name: "Opieka medyczna" },
  { id: 252, name: "Opieka nad dziećmi i osobami starszymi" },
  { id: 253, name: "Opony" },
  { id: 254, name: "Optyka, instrumenty optyczne, okulary" },
  { id: 255, name: "Organizacja kongresów, sympozjów, konferencji" },
  { id: 256, name: "Ośrodki szkoleniowo-wypoczynkowe" },
  { id: 257, name: "Osuszanie, ocieplanie" },
  { id: 258, name: "Oświetlenie, lampy" },
  { id: 259, name: "Outsourcing" },
  { id: 260, name: "Owoce i warzywa" },
  { id: 261, name: "Ozdoby świąteczne" },
  { id: 262, name: "Ozdoby szklane" },
  { id: 263, name: "Paliwa, oleje, smary" },
  { id: 264, name: "Papier i wyroby papierowe" },
  { id: 265, name: "Parapety" },
  { id: 266, name: "Parasole" },
  { id: 267, name: "Parki wodne" },
  { id: 268, name: "Parkingi" },
  { id: 269, name: "Pasmanteria" },
  { id: 270, name: "Pasze" },
  { id: 271, name: "Pensjonaty, ośrodki wczasowe, schroniska" },
  { id: 272, name: "Pieczarkarnie" },
  { id: 273, name: "Piekarnie" },
  { id: 274, name: "Pirotechnika" },
  { id: 275, name: "Pizzerie" },
  { id: 276, name: "Place zabaw" },
  { id: 277, name: "Plastycy" },
  { id: 278, name: "Pneumatyka, sprężarki, kompresory" },
  { id: 279, name: "Poczta, usługi kurierskie" },
  { id: 280, name: "Podnośniki i transportery" },
  { id: 281, name: "Podłogi, parkiety, posadzki" },
  { id: 282, name: "Pokoje gościnne, domki letniskowe" },
  { id: 283, name: "Pokrowce, plandeki" },
  { id: 284, name: "Pomiary, urządzenia pomiarowe" },
  { id: 285, name: "Pomoc drogowa, holowanie" },
  { id: 286, name: "Pompy" },
  { id: 287, name: "Porty, usługi portowe" },
  { id: 288, name: "Pozostałe" },
  { id: 289, name: "Ppoż., sprzęt ratowniczy i gaśniczy" },
  { id: 290, name: "Prace ziemne i uzbrajanie terenu" },
  { id: 291, name: "Pralnie, farbiarnie, magiel" },
  { id: 292, name: "Prawo, kancelarie i radcy prawni" },
  { id: 293, name: "Prezenty" },
  { id: 294, name: "Produkcja" },
  { id: 295, name: "Produkcja filmów" },
  { id: 296, name: "Projektowanie stron internetowych" },
  { id: 297, name: "Przedszkola" },
  { id: 298, name: "Przędza i włóczka" },
  { id: 299, name: "Przemysł metalurgiczny" },
  { id: 300, name: "Przemysłowe maszyny i urządzenia" },
  { id: 301, name: "Przeprowadzki" },
  { id: 302, name: "Przetwórstwo spożywcze" },
  { id: 303, name: "Przychodnie, poradnie, gabinety lekarskie" },
  { id: 304, name: "Przyczepy, naczepy" },
  { id: 305, name: "Psychologia, psychoterapia" },
  { id: 306, name: "Pszczelarskie artykuły" },
  { id: 307, name: "Public Relations" },
  { id: 308, name: "Płyty, kasety, CD, DVD" },
  { id: 309, name: "Rajstopy, pończochy, skarpety" },
  { id: 310, name: "Recycling" },
  { id: 311, name: "Rehabilitacja, masaż" },
  { id: 312, name: "Rehabilitacyjny i medyczny sprzęt" },
  { id: 313, name: "Reklama i marketing" },
  { id: 314, name: "Reklama, Poligrafia" },
  { id: 315, name: "Remonty i usługi budowlane" },
  { id: 316, name: "Restauracje, bary, puby" },
  { id: 317, name: "Rewidenci" },
  { id: 318, name: "Rolnicze maszyny, artykuły" },
  { id: 319, name: "Rowery" },
  { id: 320, name: "RTV, wideo" },
  { id: 321, name: "Rury, kształtki, złączki" },
  { id: 322, name: "Rusztowania, szalunki" },
  { id: 323, name: "Ryby" },
  { id: 324, name: "Rzeczoznawcy" },
  { id: 327, name: "Salony samochodowe" },
  { id: 328, name: "Sanatoria, uzdrowiska" },
  { id: 329, name: "Sauny" },
  { id: 330, name: "Schody, poręcze, balustrady" },
  { id: 331, name: "Sejfy, kasy pancerne" },
  { id: 332, name: "Silniki" },
  { id: 333, name: "Siłownie" },
  { id: 334, name: "Sklepy internetowe" },
  { id: 335, name: "Skóry naturalne i sztuczne" },
  { id: 336, name: "Soki, napoje, woda" },
  { id: 337, name: "Solaria" },
  { id: 338, name: "Spawalnicze urządzenia, materiały, usługi" },
  { id: 339, name: "Sport i rekreacja" },
  { id: 340, name: "Spółdzielnie mieszkaniowe" },
  { id: 341, name: "Sprzątanie" },
  { id: 342, name: "Sprzedaż biletów" },
  { id: 343, name: "Środki ochrony roślin" },
  { id: 344, name: "Śruby, wkręty, nakrętki, nity" },
  { id: 345, name: "Stacje radiowe, telewizyjne, telewizja kablowa" },
  { id: 346, name: "Stemple, datowniki, pieczątki" },
  { id: 347, name: "Stocznie" },
  { id: 348, name: "Stomatolodzy, protetycy, ortodonci" },
  { id: 349, name: "Stowarzyszenia, kluby, związki, fundacje" },
  { id: 350, name: "Studia tatuażu" },
  { id: 351, name: "Studnie, studniarstwo" },
  { id: 352, name: "Surowce do kosmetyków" },
  { id: 353, name: "Świece, znicze" },
  { id: 354, name: "Systemy dźwiękowe i nagłośnieniowe" },
  { id: 355, name: "Szklarze" },
  { id: 356, name: "Szkolenia, kursy" },
  { id: 357, name: "Szkoły" },
  { id: 358, name: "Szkoły językowe" },
  { id: 359, name: "Szkoły podstawowe i gimnazja" },
  { id: 360, name: "Szkoły pomaturalne i policealne" },
  { id: 361, name: "Szkoły ponadgimnazjalne" },
  { id: 362, name: "Szkoły wyższe" },
  { id: 363, name: "Szkło, wyroby szklane" },
  { id: 364, name: "Szpitale" },
  { id: 365, name: "Sztuczna biżuteria, ozdoby" },
  { id: 366, name: "Tabliczki" },
  { id: 367, name: "Tapety" },
  { id: 368, name: "Targi, wystawy" },
  { id: 369, name: "Tartaki" },
  { id: 370, name: "Taśmy przenośnikowe" },
  { id: 371, name: "Taśmy samoprzylepne" },
  { id: 372, name: "Taxi" },
  { id: 373, name: "Teatry, filharmonie, opery" },
  { id: 374, name: "Technologia bezprzewodowa" },
  { id: 375, name: "Telefoniczny sprzęt, centrale" },
  { id: 376, name: "Telefony komórkowe" },
  { id: 377, name: "Telekomunikacja" },
  { id: 378, name: "Telemarketing" },
  { id: 379, name: "Telewizja przemysłowa" },
  { id: 380, name: "Telewizja, sprzęt, montaż, oprogramowanie" },
  { id: 381, name: "Tkaniny, dzianiny, płótna" },
  { id: 382, name: "Tokarstwo" },
  { id: 383, name: "Torby podróżne, torebki, nesesery, walizki" },
  { id: 384, name: "Towarzystwa emerytalne" },
  { id: 385, name: "Transport, spedycja" },
  { id: 386, name: "Turystyka" },
  { id: 387, name: "Tworzywa sztuczne" },
  { id: 388, name: "Tytoń i artykuły tytoniowe" },
  { id: 389, name: "Tłumaczenia" },
  { id: 390, name: "Ubezpieczenia" },
  { id: 391, name: "Upominki" },
  { id: 392, name: "Urządzenia czyszczące, myjące" },
  { id: 393, name: "urządzenia, instrumenty oraz wyroby medyczne" },
  { id: 394, name: "Uszczelki, materiały uszczelniające" },
  { id: 395, name: "Usługi biurowe" },
  { id: 396, name: "Usługi konsultingowe" },
  { id: 397, name: "Usługi pogrzebowe" },
  { id: 398, name: "Utensylia, artykuły pogrzebowe" },
  { id: 399, name: "Wagi elektroniczne" },
  { id: 400, name: "Warsztaty samochodowe, serwisy naprawcze" },
  { id: 401, name: "Wędkarskie artykuły" },
  { id: 402, name: "Weterynaria" },
  { id: 403, name: "Węże" },
  { id: 404, name: "Wideo, DVD" },
  { id: 405, name: "Wideofilmowanie" },
  { id: 406, name: "Wiklina, trzcina, bambus" },
  { id: 407, name: "Windykacja i obrót wierzytelnościami" },
  { id: 408, name: "Witraże" },
  { id: 409, name: "Woda" },
  { id: 410, name: "Wodociągi, kanalizacje" },
  { id: 411, name: "Wydawnictwa" },
  { id: 412, name: "Wyroby garmażeryjne" },
  { id: 413, name: "Wyroby gumowe" },
  { id: 414, name: "Wyroby hutnicze" },
  { id: 415, name: "Wyroby jubilerskie" },
  { id: 416, name: "Wysokościowe prace" },
  { id: 417, name: "Wywóz śmieci, odpadów" },
  { id: 418, name: "Włókiennictwo" },
  { id: 419, name: "Zabawki" },
  { id: 420, name: "Zabytki" },
  { id: 421, name: "Żaluzje, markizy, rolety" },
  { id: 422, name: "Zamki, kłódki, klucze, blokady" },
  { id: 423, name: "Zaopatrzenie gastronomiczne" },
  { id: 424, name: "Zapałki, zapalniczki" },
  { id: 425, name: "Zarządzanie" },
  { id: 426, name: "Zboża" },
  { id: 427, name: "Zdrowa żywność" },
  { id: 428, name: "Zegary, zegarki, paski do zegarków" },
  { id: 429, name: "Żegluga" },
  { id: 430, name: "Zielarstwo" },
  { id: 431, name: "Znaki drogowe" },
  { id: 432, name: "Znakowanie" },
  { id: 433, name: "Zwierzęta" },
  { id: 434, name: "Żłobki" },
  { id: 435, name: "Złomowanie pojazdów, autokasacja" },
]
