export const AllIndustries = [
  { value: 325, label: "Salony fryzjerskie" },
  { value: 326, label: "Salony kosmetyczne, odnowa biologiczna, SPA" },
  { value: 436, label: "Salony makijażu" },
  { value: 437, label: "Serwisy komputerowe" },
  { value: 1, label: "Administracja państwowa" },
  { value: 2, label: "Aerozole" },
  { value: 3, label: "AGD" },
  { value: 4, label: "Agencja aktorska, aktorzy" },
  { value: 5, label: "Agencja filmowa" },
  { value: 6, label: "Agencja Reklamowa" },
  { value: 7, label: "Agencja turystyczna" },
  { value: 8, label: "Agencje artystyczne" },
  { value: 9, label: "Agencje modelek i hostess" },
  { value: 10, label: "Agencje, składy celne" },
  { value: 11, label: "Agroturystyka" },
  { value: 12, label: "Akumulatory, baterie, źródła zasilania" },
  { value: 13, label: "Alarmy, zabezpieczenia antywłamaniowe" },
  { value: 14, label: "Anteny" },
  { value: 15, label: "Antyki, dzieła sztuki" },
  { value: 16, label: "Antykorozyjne roboty, zabezpieczenia" },
  { value: 17, label: "Antykwariaty" },
  { value: 18, label: "Aparaty słuchowe, implanty ślimakowe" },
  { value: 19, label: "Apartamenty" },
  { value: 20, label: "Apteki" },
  { value: 21, label: "Architekci" },
  { value: 22, label: "Architektura krajobrazu" },
  { value: 23, label: "Architektura wnętrz" },
  { value: 24, label: "Archiwizacyjne usługi" },
  { value: 25, label: "Armatura przemysłowa" },
  { value: 26, label: "Artykuły dziecięce" },
  { value: 27, label: "Artykuły jednorazowe, higieniczne" },
  { value: 28, label: "Artykuły jeździeckie" },
  { value: 29, label: "Artykuły pościelowe, ręczniki, koce" },
  { value: 30, label: "Artykuły ślubne i weselne" },
  { value: 31, label: "Artykuły spożywcze" },
  { value: 32, label: "Artykuły szkolne, biurowe" },
  { value: 33, label: "Audiowizualne systemy" },
  { value: 34, label: "Audytorskie usługi" },
  { value: 35, label: "Automaty do sprzedaży" },
  { value: 36, label: "Automatyka przemysłowa" },
  { value: 37, label: "Autoryzowany serwis samochodowy" },
  { value: 38, label: "Badanie rynku i opinii publicznej" },
  { value: 39, label: "Banki" },
  { value: 40, label: "Baseny, fontanny" },
  { value: 41, label: "Bazy danych, usługi informacyjne, wywiadownie" },
  { value: 42, label: "Beton" },
  { value: 43, label: "BHP" },
  { value: 44, label: "Biblioteki, czytelnie" },
  { value: 45, label: "Bielizna" },
  { value: 46, label: "Biura ogłoszeń" },
  { value: 47, label: "Biura patentowe" },
  { value: 48, label: "Biura podróży" },
  { value: 49, label: "Biura pośrednictwa pracy" },
  { value: 50, label: "Biura projektów" },
  { value: 51, label: "Biura rachunkowe, doradztwo podatkowe" },
  { value: 52, label: "Blacharstwo, lakiernictwo pojazdowe" },
  { value: 53, label: "Bramy, kraty, ogrodzenia" },
  { value: 54, label: "Brukarstwo" },
  { value: 55, label: "Budownictwo" },
  { value: 56, label: "Campingi" },
  { value: 57, label: "Catering" },
  { value: 58, label: "Centra handlowe, supermarkety, hipermarkety" },
  { value: 59, label: "Ceramika, porcelana" },
  { value: 60, label: "Certyfikacja i kontrola jakości" },
  { value: 61, label: "Certyfikaty energetyczne" },
  { value: 62, label: "Chemia" },
  { value: 63, label: "Chirurgia" },
  { value: 64, label: "Ciepłownictwo, energetyka cieplna" },
  { value: 65, label: "Cukiernictwo" },
  { value: 66, label: "Cukrownie" },
  { value: 67, label: "Cyrki, wesołe miasteczka" },
  { value: 68, label: "Dachy" },
  { value: 69, label: "Dekoracje, wyposażenie wnętrz" },
  { value: 70, label: "Detektywistyczne usługi" },
  { value: 71, label: "Deweloperzy" },
  { value: 72, label: "Dezynfekcja, dezynsekcja, deratyzacja" },
  { value: 73, label: "Dietetyka, odchudzanie" },
  { value: 74, label: "Domy kultury" },
  { value: 75, label: "Domy mediowe" },
  { value: 76, label: "Doradztwo" },
  { value: 77, label: "Drewniane domy" },
  { value: 78, label: "Drewno, wyroby drewniane i drewnopochodne" },
  { value: 79, label: "Drób" },
  { value: 80, label: "Drogi, mosty" },
  {
    value: 81,
    label: "Drukarki, urządzenia peryferyjne, materiały eksploatacyjne",
  },
  { value: 82, label: "Drukarnie, poligrafia" },
  { value: 83, label: "Drukarskie akcesoria, materiały, maszyny" },
  { value: 84, label: "Drzwi" },
  { value: 85, label: "Dyskoteki, kluby" },
  { value: 86, label: "Dywany, wykładziny" },
  { value: 87, label: "Działalność twórcza" },
  { value: 88, label: "Dźwigi i urządzenia dźwigowe" },
  { value: 89, label: "Ekspertyzy, wdrożenia, analizy" },
  { value: 90, label: "Elektroizolacje" },
  { value: 91, label: "Elektronika" },
  { value: 92, label: "Elektrotechnika" },
  { value: 93, label: "Elektrownie" },
  { value: 94, label: "Energetyka" },
  { value: 95, label: "Etykiety, naklejki, emblematy" },
  { value: 96, label: "Farby, lakiery, emalie" },
  { value: 97, label: "Farmaceutyczne produkty" },
  { value: 98, label: "Filmy" },
  { value: 99, label: "Filtry, filtry powietrza" },
  { value: 100, label: "Finansowe usługi" },
  { value: 101, label: "Firany, zasłony" },
  { value: 102, label: "Fitness" },
  { value: 103, label: "Folia i artykuły foliowe" },
  { value: 104, label: "Fotografia" },
  { value: 105, label: "Fundusze inwestycyjne" },
  { value: 106, label: "Fundusze unijne" },
  { value: 107, label: "Galanteria skórzana i z tworzyw sztucznych" },
  { value: 108, label: "Galerie" },
  { value: 109, label: "Gastronomia" },
  { value: 110, label: "Gaz" },
  { value: 111, label: "Gazety i czasopisma" },
  { value: 112, label: "Gazy techniczne" },
  { value: 113, label: "Geodezja, plany, mapy" },
  { value: 114, label: "Glazura i terakota" },
  { value: 115, label: "Gospodarka odpadami, surowce wtórne" },
  { value: 116, label: "Grawerowanie" },
  { value: 117, label: "Grzyby" },
  { value: 118, label: "Hale stalowe" },
  { value: 119, label: "Handel" },
  { value: 120, label: "Hotele, motele" },
  { value: 121, label: "Hurtownie" },
  { value: 122, label: "Hydraulika siłowa" },
  { value: 123, label: "Imprezy, przyjęcia" },
  { value: 124, label: "Informatyka" },
  { value: 125, label: "Instalacje elektryczne, urządzenia" },
  { value: 126, label: "Instalacje grzewcze i ogrzewanie" },
  { value: 127, label: "Instalacje i urządzenia gazowe" },
  { value: 128, label: "Instalacje i urządzenia sanitarne" },
  { value: 129, label: "Instalacje przeciwpożarowe" },
  { value: 130, label: "Instalacje wodno-kanalizacyjne" },
  { value: 131, label: "Instrumenty muzyczne" },
  { value: 132, label: "Instytuty Wojskowe" },
  { value: 133, label: "Instytuty, ośrodki badawczo rozwojowe" },
  { value: 134, label: "Internet i usługi hostingowe" },
  { value: 135, label: "Izolacje, termoizolacje" },
  { value: 136, label: "Jachty, łodzie, statki" },
  { value: 137, label: "Kable, przewody, światłowody" },
  { value: 138, label: "Kadry i płace" },
  { value: 139, label: "Kalendarze" },
  { value: 140, label: "Kamieniarstwo" },
  { value: 141, label: "Kantory, lombardy" },
  { value: 142, label: "Kartki okolicznościowe, pocztówki" },
  { value: 143, label: "Kasy fiskalne" },
  { value: 144, label: "Katalog stron internetowych" },
  { value: 145, label: "Kawa i herbata" },
  { value: 146, label: "Kawiarnie" },
  { value: 147, label: "Kina" },
  { value: 148, label: "Kleje, żywice" },
  { value: 149, label: "Klimatyzacja, wentylacja i chłodnictwo" },
  { value: 150, label: "Kolejowy tabor" },
  { value: 151, label: "Kolektory słoneczne" },
  { value: 152, label: "Kominki, piece, kotły" },
  { value: 153, label: "Kominy, usługi kominiarskie" },
  { value: 154, label: "Komisy samochodowe" },
  { value: 155, label: "Komputery, oprogramowanie, akcesoria" },
  { value: 156, label: "Komunikacja, transport pasażerski" },
  { value: 157, label: "Konstrukcje metalowe, aluminiowe, stalowe" },
  { value: 158, label: "Kopalnie" },
  { value: 159, label: "Kosmetyki" },
  { value: 160, label: "Krawaty" },
  { value: 161, label: "Krawiectwo, haft" },
  { value: 162, label: "Kredyty" },
  { value: 163, label: "Księgarnie" },
  { value: 164, label: "Księgowość" },
  { value: 165, label: "Kwiaciarnie" },
  { value: 166, label: "Kwiaty, rośliny sztuczne" },
  { value: 167, label: "Laboratoria" },
  { value: 168, label: "Lakierowanie proszkowe" },
  { value: 169, label: "Lakierowanie, malowanie" },
  { value: 170, label: "Leasing" },
  { value: 171, label: "Lekarze" },
  { value: 172, label: "Leśnictwo" },
  { value: 173, label: "Lody" },
  { value: 174, label: "Lotnictwo" },
  { value: 175, label: "Łańcuchy" },
  { value: 176, label: "Łazienki" },
  { value: 177, label: "Łożyska" },
  { value: 178, label: "Magazyny, systemy magazynowe, logistyka" },
  { value: 179, label: "Magnesy, elektromagnesy, magnetyzery" },
  { value: 180, label: "Maklerskie biura" },
  { value: 181, label: "Maszty, flagi, sztandary" },
  { value: 182, label: "Maszyny budowlane" },
  { value: 183, label: "Maszyny dla przemysłu spożywczego, mięsnego" },
  { value: 184, label: "Maszyny do obróbki drewna" },
  { value: 185, label: "Maszyny do obróbki metali" },
  { value: 186, label: "Maszyny i urządzenia górnicze" },
  { value: 187, label: "Maszyny szwalnicze, urządzenia prasowalnicze" },
  { value: 188, label: "Materace" },
  { value: 189, label: "Materiały budowlane" },
  { value: 190, label: "Meble" },
  { value: 191, label: "Meble biurowe" },
  { value: 192, label: "Meble kuchenne" },
  { value: 193, label: "Meble metalowe" },
  { value: 194, label: "Meble ogrodowe" },
  { value: 195, label: "Meble szkolne" },
  { value: 196, label: "Meble tapicerowane" },
  { value: 197, label: "Medycyna" },
  { value: 198, label: "Medycyna naturalna" },
  { value: 199, label: "Mięso, wędliny, drób" },
  { value: 200, label: "Militaria, artykuły wojskowe" },
  { value: 201, label: "Mleko i produkty mleczne" },
  { value: 202, label: "Moda ślubna, komunijna" },
  { value: 203, label: "Modelarstwo" },
  { value: 204, label: "Monitoring" },
  { value: 205, label: "Motocykle, quady, skutery" },
  { value: 206, label: "Motoryzacja, akcesoria, usługi motoryzacyjne" },
  { value: 207, label: "Mrożonki" },
  { value: 208, label: "Muzea" },
  { value: 209, label: "Muzyczne zespoły" },
  { value: 210, label: "Myjnie samochodowe" },
  { value: 211, label: "Myślistwo" },
  { value: 212, label: "Młyny" },
  { value: 213, label: "Nadzór budowlany" },
  { value: 214, label: "Nakrycia głowy, rękawiczki, szaliki" },
  { value: 215, label: "Namioty, hale" },
  { value: 216, label: "Napoje alkoholowe" },
  { value: 217, label: "Narzędzia, elektronarzędzia" },
  { value: 218, label: "Nasiona, sadzonki" },
  { value: 219, label: "Nauka jazdy" },
  { value: 220, label: "Nauka tańca" },
  { value: 221, label: "Nawigacja" },
  { value: 222, label: "Nawozy" },
  { value: 223, label: "Nieruchomości" },
  { value: 224, label: "Obiekty sportowe" },
  { value: 225, label: "Obrazy, oprawa obrazów" },
  { value: 226, label: "Obróbka metali, wyroby metalowe, metale kolorowe" },
  { value: 227, label: "Obróbka skrawanie, szlifowanie i frezowanie" },
  { value: 228, label: "Obuwie" },
  { value: 229, label: "Ochrona osób i mienia" },
  { value: 230, label: "Ochrona środowiska, ekologia" },
  { value: 231, label: "Oczyszczanie ścieków" },
  { value: 232, label: "Odkurzacze centralne" },
  { value: 233, label: "Odzież" },
  { value: 234, label: "Odzież ciążowa" },
  { value: 235, label: "Odzież damska" },
  { value: 236, label: "Odzież dziecięca, młodzieżowa" },
  { value: 237, label: "Odzież jeansowa" },
  { value: 238, label: "Odzież męska" },
  { value: 239, label: "Odzież ochronna i robocza" },
  { value: 240, label: "Odzież skórzana" },
  { value: 241, label: "Odzież sportowa" },
  { value: 242, label: "Odzież używana" },
  { value: 243, label: "Odżywki i suplementy" },
  { value: 244, label: "Ogrodnicze usługi, artykuły, sprzęt" },
  { value: 245, label: "Ogrody botaniczne, zoologiczne" },
  { value: 246, label: "Okna" },
  { value: 247, label: "Okucia" },
  { value: 248, label: "Opakowania" },
  { value: 249, label: "Opakowania i pojemniki" },
  { value: 250, label: "Opałowe materiały" },
  { value: 251, label: "Opieka medyczna" },
  { value: 252, label: "Opieka nad dziećmi i osobami starszymi" },
  { value: 253, label: "Opony" },
  { value: 254, label: "Optyka, instrumenty optyczne, okulary" },
  { value: 255, label: "Organizacja kongresów, sympozjów, konferencji" },
  { value: 256, label: "Ośrodki szkoleniowo-wypoczynkowe" },
  { value: 257, label: "Osuszanie, ocieplanie" },
  { value: 258, label: "Oświetlenie, lampy" },
  { value: 259, label: "Outsourcing" },
  { value: 260, label: "Owoce i warzywa" },
  { value: 261, label: "Ozdoby świąteczne" },
  { value: 262, label: "Ozdoby szklane" },
  { value: 263, label: "Paliwa, oleje, smary" },
  { value: 264, label: "Papier i wyroby papierowe" },
  { value: 265, label: "Parapety" },
  { value: 266, label: "Parasole" },
  { value: 267, label: "Parki wodne" },
  { value: 268, label: "Parkingi" },
  { value: 269, label: "Pasmanteria" },
  { value: 270, label: "Pasze" },
  { value: 271, label: "Pensjonaty, ośrodki wczasowe, schroniska" },
  { value: 272, label: "Pieczarkarnie" },
  { value: 273, label: "Piekarnie" },
  { value: 274, label: "Pirotechnika" },
  { value: 275, label: "Pizzerie" },
  { value: 276, label: "Place zabaw" },
  { value: 277, label: "Plastycy" },
  { value: 278, label: "Pneumatyka, sprężarki, kompresory" },
  { value: 279, label: "Poczta, usługi kurierskie" },
  { value: 280, label: "Podnośniki i transportery" },
  { value: 281, label: "Podłogi, parkiety, posadzki" },
  { value: 282, label: "Pokoje gościnne, domki letniskowe" },
  { value: 283, label: "Pokrowce, plandeki" },
  { value: 284, label: "Pomiary, urządzenia pomiarowe" },
  { value: 285, label: "Pomoc drogowa, holowanie" },
  { value: 286, label: "Pompy" },
  { value: 287, label: "Porty, usługi portowe" },
  { value: 288, label: "Pozostałe" },
  { value: 289, label: "Ppoż., sprzęt ratowniczy i gaśniczy" },
  { value: 290, label: "Prace ziemne i uzbrajanie terenu" },
  { value: 291, label: "Pralnie, farbiarnie, magiel" },
  { value: 292, label: "Prawo, kancelarie i radcy prawni" },
  { value: 293, label: "Prezenty" },
  { value: 294, label: "Produkcja" },
  { value: 295, label: "Produkcja filmów" },
  { value: 296, label: "Projektowanie stron internetowych" },
  { value: 297, label: "Przedszkola" },
  { value: 298, label: "Przędza i włóczka" },
  { value: 299, label: "Przemysł metalurgiczny" },
  { value: 300, label: "Przemysłowe maszyny i urządzenia" },
  { value: 301, label: "Przeprowadzki" },
  { value: 302, label: "Przetwórstwo spożywcze" },
  { value: 303, label: "Przychodnie, poradnie, gabinety lekarskie" },
  { value: 304, label: "Przyczepy, naczepy" },
  { value: 305, label: "Psychologia, psychoterapia" },
  { value: 306, label: "Pszczelarskie artykuły" },
  { value: 307, label: "Public Relations" },
  { value: 308, label: "Płyty, kasety, CD, DVD" },
  { value: 309, label: "Rajstopy, pończochy, skarpety" },
  { value: 310, label: "Recycling" },
  { value: 311, label: "Rehabilitacja, masaż" },
  { value: 312, label: "Rehabilitacyjny i medyczny sprzęt" },
  { value: 313, label: "Reklama i marketing" },
  { value: 314, label: "Reklama, Poligrafia" },
  { value: 315, label: "Remonty i usługi budowlane" },
  { value: 316, label: "Restauracje, bary, puby" },
  { value: 317, label: "Rewidenci" },
  { value: 318, label: "Rolnicze maszyny, artykuły" },
  { value: 319, label: "Rowery" },
  { value: 320, label: "RTV, wideo" },
  { value: 321, label: "Rury, kształtki, złączki" },
  { value: 322, label: "Rusztowania, szalunki" },
  { value: 323, label: "Ryby" },
  { value: 324, label: "Rzeczoznawcy" },
  { value: 327, label: "Salony samochodowe" },
  { value: 328, label: "Sanatoria, uzdrowiska" },
  { value: 329, label: "Sauny" },
  { value: 330, label: "Schody, poręcze, balustrady" },
  { value: 331, label: "Sejfy, kasy pancerne" },
  { value: 332, label: "Silniki" },
  { value: 333, label: "Siłownie" },
  { value: 334, label: "Sklepy internetowe" },
  { value: 335, label: "Skóry naturalne i sztuczne" },
  { value: 336, label: "Soki, napoje, woda" },
  { value: 337, label: "Solaria" },
  { value: 338, label: "Spawalnicze urządzenia, materiały, usługi" },
  { value: 339, label: "Sport i rekreacja" },
  { value: 340, label: "Spółdzielnie mieszkaniowe" },
  { value: 341, label: "Sprzątanie" },
  { value: 342, label: "Sprzedaż biletów" },
  { value: 343, label: "Środki ochrony roślin" },
  { value: 344, label: "Śruby, wkręty, nakrętki, nity" },
  { value: 345, label: "Stacje radiowe, telewizyjne, telewizja kablowa" },
  { value: 346, label: "Stemple, datowniki, pieczątki" },
  { value: 347, label: "Stocznie" },
  { value: 348, label: "Stomatolodzy, protetycy, ortodonci" },
  { value: 349, label: "Stowarzyszenia, kluby, związki, fundacje" },
  { value: 350, label: "Studia tatuażu" },
  { value: 351, label: "Studnie, studniarstwo" },
  { value: 352, label: "Surowce do kosmetyków" },
  { value: 353, label: "Świece, znicze" },
  { value: 354, label: "Systemy dźwiękowe i nagłośnieniowe" },
  { value: 355, label: "Szklarze" },
  { value: 356, label: "Szkolenia, kursy" },
  { value: 357, label: "Szkoły" },
  { value: 358, label: "Szkoły językowe" },
  { value: 359, label: "Szkoły podstawowe i gimnazja" },
  { value: 360, label: "Szkoły pomaturalne i policealne" },
  { value: 361, label: "Szkoły ponadgimnazjalne" },
  { value: 362, label: "Szkoły wyższe" },
  { value: 363, label: "Szkło, wyroby szklane" },
  { value: 364, label: "Szpitale" },
  { value: 365, label: "Sztuczna biżuteria, ozdoby" },
  { value: 366, label: "Tabliczki" },
  { value: 367, label: "Tapety" },
  { value: 368, label: "Targi, wystawy" },
  { value: 369, label: "Tartaki" },
  { value: 370, label: "Taśmy przenośnikowe" },
  { value: 371, label: "Taśmy samoprzylepne" },
  { value: 372, label: "Taxi" },
  { value: 373, label: "Teatry, filharmonie, opery" },
  { value: 374, label: "Technologia bezprzewodowa" },
  { value: 375, label: "Telefoniczny sprzęt, centrale" },
  { value: 376, label: "Telefony komórkowe" },
  { value: 377, label: "Telekomunikacja" },
  { value: 378, label: "Telemarketing" },
  { value: 379, label: "Telewizja przemysłowa" },
  { value: 380, label: "Telewizja, sprzęt, montaż, oprogramowanie" },
  { value: 381, label: "Tkaniny, dzianiny, płótna" },
  { value: 382, label: "Tokarstwo" },
  { value: 383, label: "Torby podróżne, torebki, nesesery, walizki" },
  { value: 384, label: "Towarzystwa emerytalne" },
  { value: 385, label: "Transport, spedycja" },
  { value: 386, label: "Turystyka" },
  { value: 387, label: "Tworzywa sztuczne" },
  { value: 388, label: "Tytoń i artykuły tytoniowe" },
  { value: 389, label: "Tłumaczenia" },
  { value: 390, label: "Ubezpieczenia" },
  { value: 391, label: "Upominki" },
  { value: 392, label: "Urządzenia czyszczące, myjące" },
  { value: 393, label: "urządzenia, instrumenty oraz wyroby medyczne" },
  { value: 394, label: "Uszczelki, materiały uszczelniające" },
  { value: 395, label: "Usługi biurowe" },
  { value: 396, label: "Usługi konsultingowe" },
  { value: 397, label: "Usługi pogrzebowe" },
  { value: 398, label: "Utensylia, artykuły pogrzebowe" },
  { value: 399, label: "Wagi elektroniczne" },
  { value: 400, label: "Warsztaty samochodowe, serwisy naprawcze" },
  { value: 401, label: "Wędkarskie artykuły" },
  { value: 402, label: "Weterynaria" },
  { value: 403, label: "Węże" },
  { value: 404, label: "Wideo, DVD" },
  { value: 405, label: "Wideofilmowanie" },
  { value: 406, label: "Wiklina, trzcina, bambus" },
  { value: 407, label: "Windykacja i obrót wierzytelnościami" },
  { value: 408, label: "Witraże" },
  { value: 409, label: "Woda" },
  { value: 410, label: "Wodociągi, kanalizacje" },
  { value: 411, label: "Wydawnictwa" },
  { value: 412, label: "Wyroby garmażeryjne" },
  { value: 413, label: "Wyroby gumowe" },
  { value: 414, label: "Wyroby hutnicze" },
  { value: 415, label: "Wyroby jubilerskie" },
  { value: 416, label: "Wysokościowe prace" },
  { value: 417, label: "Wywóz śmieci, odpadów" },
  { value: 418, label: "Włókiennictwo" },
  { value: 419, label: "Zabawki" },
  { value: 420, label: "Zabytki" },
  { value: 421, label: "Żaluzje, markizy, rolety" },
  { value: 422, label: "Zamki, kłódki, klucze, blokady" },
  { value: 423, label: "Zaopatrzenie gastronomiczne" },
  { value: 424, label: "Zapałki, zapalniczki" },
  { value: 425, label: "Zarządzanie" },
  { value: 426, label: "Zboża" },
  { value: 427, label: "Zdrowa żywność" },
  { value: 428, label: "Zegary, zegarki, paski do zegarków" },
  { value: 429, label: "Żegluga" },
  { value: 430, label: "Zielarstwo" },
  { value: 431, label: "Znaki drogowe" },
  { value: 432, label: "Znakowanie" },
  { value: 433, label: "Zwierzęta" },
  { value: 434, label: "Żłobki" },
  { value: 435, label: "Złomowanie pojazdów, autokasacja" },
]
