import { Translates } from "@common/Translates"

const generateMenuInfo = ({
  handleClickLogin,
  loginVisible,
  userServicesVisible,
  user,
  handleClickUserServicesVisible,
  location,
  isMobileSize,
  handleMenuOpen,
  isBarSize,
  siteProps,
  registrationVisible,
  handleClickRegister,
  handleUserProfil,
}) => {
  const pathname = location.pathname

  const currentTexts = Translates[siteProps.language]

  return [
    {
      title: currentTexts.info.createUserAccount.title,
      alert: currentTexts.info.createUserAccount.alert,
      steps: [
        {
          title: `${currentTexts.info.createUserAccount.steps[0].title} ${currentTexts.buttons.register}${currentTexts.info.createUserAccount.steps[0].title2}`,
          path: null,
          pathValid: true,
          pathRouteEnable: false,
          pathRouteName: null,
          elementId: "RegistrationUserButton",
          elementName: `${currentTexts.info.createUserAccount.steps[0].button} ${currentTexts.buttons.register}`,
          elementValid: !!!user,
          elementHandler: isBarSize ? handleMenuOpen : null,
          lightFromEffect: true,
        },
        {
          title: currentTexts.info.createUserAccount.steps[1].title,
          path: null,
          pathValid: true,
          pathRouteEnable: false,
          pathRouteName: null,
          elementId: "RegistrationContent",
          elementName: currentTexts.info.createUserAccount.steps[1].button,
          elementValid: !registrationVisible && !!!user,
          elementHandler: handleClickRegister,
          lightFromEffect: false,
        },
      ],
    },
    {
      title: currentTexts.info.loginUserAccount.title,
      alert: currentTexts.info.loginUserAccount.alert,
      steps: [
        {
          title: `${currentTexts.info.loginUserAccount.steps[0].title} ${currentTexts.buttons.logIn}${currentTexts.info.loginUserAccount.steps[0].title2}`,
          path: null,
          pathValid: true,
          pathRouteEnable: false,
          pathRouteName: null,
          elementId: "LoginUserButton",
          elementName: `${currentTexts.info.loginUserAccount.steps[0].button} ${currentTexts.buttons.logIn}`,
          elementValid: !!!user,
          elementHandler: isBarSize ? handleMenuOpen : null,
          lightFromEffect: true,
        },
        {
          title: currentTexts.info.loginUserAccount.steps[1].title,
          path: null,
          pathValid: true,
          pathRouteEnable: false,
          pathRouteName: null,
          elementId: "LoginUserContent",
          elementName: currentTexts.info.loginUserAccount.steps[1].button,
          elementValid: !loginVisible && !!!user,
          elementHandler: handleClickLogin,
          lightFromEffect: false,
        },
      ],
    },
    {
      title: currentTexts.info.logoutUserAccount.title,
      alert: currentTexts.info.logoutUserAccount.alert,
      steps: [
        {
          title: `${currentTexts.info.logoutUserAccount.steps[0].title} ${currentTexts.buttons.logOut}${currentTexts.info.logoutUserAccount.steps[0].title2}`,
          path: null,
          pathValid: true,
          pathRouteEnable: false,
          pathRouteName: null,
          elementId: "LogoutUserButton",
          elementName: `${currentTexts.info.logoutUserAccount.steps[0].button} ${currentTexts.buttons.logOut}`,
          elementValid: !!user,
          elementHandler: isBarSize ? handleMenuOpen : null,
          lightFromEffect: true,
        },
      ],
    },
    {
      title: currentTexts.info.languageMode.title,
      alert: currentTexts.info.languageMode.alert,
      steps: [
        {
          title: `${currentTexts.info.languageMode.steps[0].title} ${currentTexts.buttons.language}${currentTexts.info.languageMode.steps[0].title2}`,
          path: null,
          pathValid: true,
          pathRouteEnable: false,
          pathRouteName: null,
          elementId: "LanguageModeButton",
          elementName: `${currentTexts.info.languageMode.steps[0].button} ${currentTexts.buttons.language}`,
          elementValid: true,
          elementHandler: handleMenuOpen,
          lightFromEffect: true,
        },
      ],
    },
    {
      title: currentTexts.info.darkMode.title,
      alert: currentTexts.info.darkMode.alert,
      steps: [
        {
          title: `${currentTexts.info.darkMode.steps[0].title} ${currentTexts.buttons.darkMode}${currentTexts.info.darkMode.steps[0].title2}`,
          path: null,
          pathValid: true,
          pathRouteEnable: false,
          pathRouteName: null,
          elementId: "DarkModeButton",
          elementName: `${currentTexts.info.darkMode.steps[0].button} ${currentTexts.buttons.darkMode}`,
          elementValid: true,
          elementHandler: handleMenuOpen,
          lightFromEffect: true,
        },
      ],
    },
    {
      title: currentTexts.info.blindMode.title,
      alert: currentTexts.info.blindMode.alert,
      steps: [
        {
          title: `${currentTexts.info.blindMode.steps[0].title} ${currentTexts.buttons.colorBlindMode}${currentTexts.info.blindMode.steps[0].title2}`,
          path: null,
          pathValid: true,
          pathRouteEnable: false,
          pathRouteName: null,
          elementId: "BlindModeButton",
          elementName: `${currentTexts.info.blindMode.steps[0].button} ${currentTexts.buttons.colorBlindMode}`,
          elementValid: true,
          elementHandler: handleMenuOpen,
          lightFromEffect: true,
        },
      ],
    },
    {
      title: currentTexts.info.checkAlerts.title,
      alert: currentTexts.info.checkAlerts.alert,
      steps: [
        {
          title: `${currentTexts.info.checkAlerts.steps[0].title}`,
          path: null,
          pathValid: true,
          pathRouteEnable: false,
          pathRouteName: null,
          elementId: "AlertsButton",
          elementName: `${currentTexts.info.checkAlerts.steps[0].button}`,
          elementValid: !!user,
          elementHandler: null,
          lightFromEffect: true,
        },
      ],
    },
    {
      title: currentTexts.info.checkStamps.title,
      alert: currentTexts.info.checkStamps.alert,
      steps: [
        {
          title: `${currentTexts.info.checkStamps.steps[0].title}`,
          path: null,
          pathValid: true,
          pathRouteEnable: false,
          pathRouteName: null,
          elementId: "StampsUserButton",
          elementName: `${currentTexts.info.checkStamps.steps[0].button}`,
          elementValid: !!user,
          elementHandler: null,
          lightFromEffect: true,
        },
      ],
    },
    {
      title: currentTexts.info.checkFavourites.title,
      alert: currentTexts.info.checkFavourites.alert,
      steps: [
        {
          title: `${currentTexts.info.checkFavourites.steps[0].title}`,
          path: null,
          pathValid: true,
          pathRouteEnable: false,
          pathRouteName: null,
          elementId: "FavouritesUserButton",
          elementName: `${currentTexts.info.checkFavourites.steps[0].button}`,
          elementValid: !!user,
          elementHandler: null,
          lightFromEffect: true,
        },
      ],
    },
    {
      title: currentTexts.info.userAccountData.title,
      alert: currentTexts.info.userAccountData.alert,
      steps: [
        {
          title: `${currentTexts.info.userAccountData.steps[0].title}`,
          path: null,
          pathValid: true,
          pathRouteEnable: false,
          pathRouteName: null,
          elementId: "UserAccountEditButton",
          elementName: `${currentTexts.info.userAccountData.steps[0].button}`,
          elementValid: !!user,
          elementHandler: isBarSize ? handleMenuOpen : null,
          lightFromEffect: true,
        },
        {
          title: `${currentTexts.info.userAccountData.steps[1].title}`,
          path: null,
          pathValid: true,
          pathRouteEnable: false,
          pathRouteName: null,
          elementId: "UserProfilContent",
          elementName: `${currentTexts.info.userAccountData.steps[1].button}`,
          elementValid: !!user,
          elementHandler: handleUserProfil,
          lightFromEffect: false,
        },
      ],
    },
    {
      title: currentTexts.info.userAccountDataChangePhone.title,
      alert: currentTexts.info.userAccountDataChangePhone.alert,
      steps: [
        {
          title: `${currentTexts.info.userAccountDataChangePhone.steps[0].title}`,
          path: null,
          pathValid: true,
          pathRouteEnable: false,
          pathRouteName: null,
          elementId: "UserAccountEditButton",
          elementName: `${currentTexts.info.userAccountDataChangePhone.steps[0].button}`,
          elementValid: !!user,
          elementHandler: isBarSize ? handleMenuOpen : null,
          lightFromEffect: true,
        },
        {
          title: `${currentTexts.info.userAccountDataChangePhone.steps[1].title}`,
          path: null,
          pathValid: true,
          pathRouteEnable: false,
          pathRouteName: null,
          elementId: "UserProfilContent",
          elementName: `${currentTexts.info.userAccountDataChangePhone.steps[1].button}`,
          elementValid: !!user,
          elementHandler: handleUserProfil,
          lightFromEffect: false,
        },
        {
          title: `${currentTexts.info.userAccountDataChangePhone.steps[2].title} ${currentTexts.buttons.editPhoneNumber}${currentTexts.info.userAccountDataChangePhone.steps[2].title2}`,
          path: null,
          pathValid: true,
          pathRouteEnable: false,
          pathRouteName: null,
          elementId: "EditUserPhoneNumberButton",
          elementName: `${currentTexts.info.userAccountDataChangePhone.steps[2].button} ${currentTexts.buttons.editPhoneNumber}`,
          elementValid: !!user,
          elementHandler: handleUserProfil,
          lightFromEffect: true,
        },
        {
          title: `${currentTexts.info.userAccountDataChangePhone.steps[3].title} ${currentTexts.buttons.save}`,
          path: null,
          pathValid: true,
          pathRouteEnable: false,
          pathRouteName: null,
          elementId: null,
          elementName: null,
          elementValid: null,
          elementHandler: null,
          lightFromEffect: false,
        },
        {
          title: `${currentTexts.info.userAccountDataChangePhone.steps[4].title}`,
          path: null,
          pathValid: true,
          pathRouteEnable: false,
          pathRouteName: null,
          elementId: "VeryfiedUserPhoneNumberButton",
          elementName: `${currentTexts.info.userAccountDataChangePhone.steps[4].button} ${currentTexts.buttons.veryfiedUserPhoneNumber}`,
          elementValid: !!user ? !!!user.phoneVerified : false,
          elementHandler: handleUserProfil,
          lightFromEffect: false,
        },
        {
          title: `${currentTexts.info.userAccountDataChangePhone.steps[5].title}`,
          path: null,
          pathValid: true,
          pathRouteEnable: false,
          pathRouteName: null,
          elementId: null,
          elementName: null,
          elementValid: null,
          elementHandler: null,
          lightFromEffect: false,
        },
      ],
    },
    {
      title: currentTexts.info.userAccountDataChangeEmail.title,
      alert: currentTexts.info.userAccountDataChangeEmail.alert,
      steps: [
        {
          title: `${currentTexts.info.userAccountDataChangeEmail.steps[0].title}`,
          path: null,
          pathValid: true,
          pathRouteEnable: false,
          pathRouteName: null,
          elementId: "UserAccountEditButton",
          elementName: `${currentTexts.info.userAccountDataChangeEmail.steps[0].button}`,
          elementValid: !!user,
          elementHandler: isBarSize ? handleMenuOpen : null,
          lightFromEffect: true,
        },
        {
          title: `${currentTexts.info.userAccountDataChangeEmail.steps[1].title}`,
          path: null,
          pathValid: true,
          pathRouteEnable: false,
          pathRouteName: null,
          elementId: "UserProfilContent",
          elementName: `${currentTexts.info.userAccountDataChangeEmail.steps[1].button}`,
          elementValid: !!user,
          elementHandler: handleUserProfil,
          lightFromEffect: false,
        },
        {
          title: `${currentTexts.info.userAccountDataChangeEmail.steps[2].title} ${currentTexts.buttons.editEmail}${currentTexts.info.userAccountDataChangeEmail.steps[2].title2}`,
          path: null,
          pathValid: true,
          pathRouteEnable: false,
          pathRouteName: null,
          elementId: "EditUserEmailButton",
          elementName: `${currentTexts.info.userAccountDataChangeEmail.steps[2].button} ${currentTexts.buttons.editEmail}`,
          elementValid: !!user,
          elementHandler: handleUserProfil,
          lightFromEffect: true,
        },
        {
          title: `${currentTexts.info.userAccountDataChangeEmail.steps[3].title} ${currentTexts.buttons.save}`,
          path: null,
          pathValid: true,
          pathRouteEnable: false,
          pathRouteName: null,
          elementId: null,
          elementName: null,
          elementValid: null,
          elementHandler: null,
          lightFromEffect: false,
        },
        {
          title: `${currentTexts.info.userAccountDataChangeEmail.steps[4].title}`,
          path: null,
          pathValid: true,
          pathRouteEnable: false,
          pathRouteName: null,
          elementId: "VeryfiedUserEmailButton",
          elementName: `${currentTexts.info.userAccountDataChangeEmail.steps[4].button} ${currentTexts.buttons.veryfiedUserEmail}`,
          elementValid: !!user ? !!!user.phoneVerified : false,
          elementHandler: handleUserProfil,
          lightFromEffect: false,
        },
        {
          title: `${currentTexts.info.userAccountDataChangeEmail.steps[5].title}`,
          path: null,
          pathValid: true,
          pathRouteEnable: false,
          pathRouteName: null,
          elementId: null,
          elementName: null,
          elementValid: null,
          elementHandler: null,
          lightFromEffect: false,
        },
      ],
    },
    {
      title: currentTexts.info.userAccountDataChangePassword.title,
      alert: currentTexts.info.userAccountDataChangePassword.alert,
      steps: [
        {
          title: `${currentTexts.info.userAccountDataChangePassword.steps[0].title}`,
          path: null,
          pathValid: true,
          pathRouteEnable: false,
          pathRouteName: null,
          elementId: "UserAccountEditButton",
          elementName: `${currentTexts.info.userAccountDataChangePassword.steps[0].button}`,
          elementValid: !!user,
          elementHandler: isBarSize ? handleMenuOpen : null,
          lightFromEffect: true,
        },
        {
          title: `${currentTexts.info.userAccountDataChangePassword.steps[1].title}`,
          path: null,
          pathValid: true,
          pathRouteEnable: false,
          pathRouteName: null,
          elementId: "UserProfilContent",
          elementName: `${currentTexts.info.userAccountDataChangePassword.steps[1].button}`,
          elementValid: !!user,
          elementHandler: handleUserProfil,
          lightFromEffect: false,
        },
        {
          title: `${currentTexts.info.userAccountDataChangePassword.steps[2].title} ${currentTexts.buttons.editPassword}${currentTexts.info.userAccountDataChangePassword.steps[2].title2}`,
          path: null,
          pathValid: true,
          pathRouteEnable: false,
          pathRouteName: null,
          elementId: "EditUserPasswordButton",
          elementName: `${currentTexts.info.userAccountDataChangePassword.steps[2].button} ${currentTexts.buttons.editPassword}`,
          elementValid: !!user,
          elementHandler: handleUserProfil,
          lightFromEffect: true,
        },
        {
          title: `${currentTexts.info.userAccountDataChangePassword.steps[3].title} ${currentTexts.buttons.save}`,
          path: null,
          pathValid: true,
          pathRouteEnable: false,
          pathRouteName: null,
          elementId: null,
          elementName: null,
          elementValid: null,
          elementHandler: null,
          lightFromEffect: false,
        },
        {
          title: `${currentTexts.info.userAccountDataChangePassword.steps[4].title}`,
          path: null,
          pathValid: true,
          pathRouteEnable: false,
          pathRouteName: null,
          elementId: null,
          elementName: null,
          elementValid: null,
          elementHandler: null,
          lightFromEffect: false,
        },
      ],
    },
    {
      title: "Gdzie znajdują się usługi firmy?",
      steps: [
        {
          title:
            "Znajdz odpowiadającą Tobie firmę, a następnie kliknij przycisk Rezerwuj",
          path: "/",
          pathValid: pathname === "/",
          pathRouteEnable: true,
          pathRouteName: "Przejdz do strony wyboru firm",
          elementId: "PlaceItem",
          elementName: "Pokaż firmy",
          elementValid: true,
          elementHandler: null,
          lightFromEffect: false,
        },
        {
          title: "Gdy wybierzesz już firmę to przejdz do usług",
          path: "/company",
          pathValid: pathname === "/company",
          pathRouteEnable: false,
          pathRouteName: null,
          elementId: "AllCategoryOfServices",
          elementName: "Pokaż usługi",
          elementValid: true,
          elementHandler: null,
          lightFromEffect: false,
        },
      ],
    },
    {
      title: "Gdzie znajdują się wszystkie rezerwację użytkownika?",
      steps: [
        {
          title: "Zaloguj się aby móc mieć dostęp do Twoich rezerwacji",
          path: null,
          pathValid: true,
          pathRouteEnable: false,
          pathRouteName: null,
          elementId: "LoginContent",
          elementName: "Przejdz do logowania",
          elementValid: !loginVisible && !!!user,
          elementHandler: handleClickLogin,
          lightFromEffect: false,
        },
        {
          title:
            "Przejdz do Twoich usług, które znajdują się w górnym menu (nawigacja) lub w rozwijanym menu bocznym",
          path: null,
          pathValid: true,
          pathRouteEnable: false,
          pathRouteName: null,
          elementId: "YourServicesButton",
          elementName: "Pokaż przycisk Twoje usługi",
          elementValid: true,
          elementHandler: isBarSize ? handleMenuOpen : null,
          lightFromEffect: true,
        },
        {
          title: "Naciśnij przycisk Twoje usługi",
          path: null,
          pathValid: true,
          pathRouteEnable: false,
          pathRouteName: null,
          elementId: "YourServicesAllButtons",
          elementName: "Przejdz do Twoich usług",
          elementValid: !userServicesVisible && !!user,
          elementHandler: handleClickUserServicesVisible,
          lightFromEffect: false,
        },
        {
          title:
            "Wszystkie Twoje rezerwacje dostępne są pod przyciskiem Rezerwacje",
          path: null,
          pathValid: true,
          pathRouteEnable: false,
          pathRouteName: null,
          elementId: "BookingHistoryButton",
          elementName: "Pokaż przycisk Rezerwacje",
          elementValid: !!user,
          elementHandler: handleClickUserServicesVisible,
          lightFromEffect: true,
        },
      ],
    },
    {
      title: "Gdzie znajdują się wszystkie serwisy użytkownika?",
      steps: [
        {
          title: "Zaloguj się aby móc mieć dostęp do Twoich rezerwacji",
          path: null,
          pathValid: true,
          pathRouteEnable: false,
          pathRouteName: null,
          elementId: "LoginContent",
          elementName: "Przejdz do logowania",
          elementValid: !loginVisible && !!!user,
          elementHandler: handleClickLogin,
          lightFromEffect: false,
        },
        {
          title:
            "Przejdz do Twoich usług, które znajdują się w górnym menu (nawigacja) lub w rozwijanym menu bocznym",
          path: null,
          pathValid: true,
          pathRouteEnable: false,
          pathRouteName: null,
          elementId: "YourServicesButton",
          elementName: "Pokaż przycisk Twoje usługi",
          elementValid: true,
          elementHandler: isBarSize ? handleMenuOpen : null,
          lightFromEffect: true,
        },
        {
          title: "Naciśnij przycisk Twoje usługi",
          path: null,
          pathValid: true,
          pathRouteEnable: false,
          pathRouteName: null,
          elementId: "YourServicesAllButtons",
          elementName: "Przejdz do Twoich usług",
          elementValid: !userServicesVisible && !!user,
          elementHandler: handleClickUserServicesVisible,
          lightFromEffect: false,
        },
        {
          title: "Wszystkie Twoje serwisy dostępne są pod przyciskiem Serwisy",
          path: null,
          pathValid: true,
          pathRouteEnable: false,
          pathRouteName: null,
          elementId: "ServicesHistoryButton",
          elementName: "Pokaż przycisk Serwisy",
          elementValid: !!user,
          elementHandler: handleClickUserServicesVisible,
          lightFromEffect: true,
        },
      ],
    },
    {
      title: "Gdzie znajdują się wszystkie dojazdy użytkownika?",
      steps: [
        {
          title: "Zaloguj się aby móc mieć dostęp do Twoich rezerwacji",
          path: null,
          pathValid: true,
          pathRouteEnable: false,
          pathRouteName: null,
          elementId: "LoginContent",
          elementName: "Przejdz do logowania",
          elementValid: !loginVisible && !!!user,
          elementHandler: handleClickLogin,
          lightFromEffect: false,
        },
        {
          title:
            "Przejdz do Twoich usług, które znajdują się w górnym menu (nawigacja) lub w rozwijanym menu bocznym",
          path: null,
          pathValid: true,
          pathRouteEnable: false,
          pathRouteName: null,
          elementId: "YourServicesButton",
          elementName: "Pokaż przycisk Twoje usługi",
          elementValid: true,
          elementHandler: isBarSize ? handleMenuOpen : null,
          lightFromEffect: true,
        },
        {
          title: "Naciśnij przycisk Twoje usługi",
          path: null,
          pathValid: true,
          pathRouteEnable: false,
          pathRouteName: null,
          elementId: "YourServicesAllButtons",
          elementName: "Przejdz do Twoich usług",
          elementValid: !userServicesVisible && !!user,
          elementHandler: handleClickUserServicesVisible,
          lightFromEffect: false,
        },
        {
          title: "Wszystkie Twoje dojazdy dostępne są pod przyciskiem Dojazdy",
          path: null,
          pathValid: true,
          pathRouteEnable: false,
          pathRouteName: null,
          elementId: "CommunitingsHistoryButton",
          elementName: "Pokaż przycisk Dojazdy",
          elementValid: !!user,
          elementHandler: handleClickUserServicesVisible,
          lightFromEffect: true,
        },
      ],
    },
  ]
}

export default generateMenuInfo
